[package]
name = "lst_common"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
thiserror.workspace = true
schemars.workspace = true
serde.workspace = true
cw20.workspace = true
cw2.workspace = true
cw20-base.workspace = true
cosmos-sdk-proto = { workspace = true }
prost = { workspace = true, default-features = false }
bech32.workspace = true
cw-storage-plus = { workspace = true }
serde_json = { workspace = true }

[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
cw-multi-test = { workspace = true, features = ["staking", "cosmwasm_2_2"] }
